name: Check
on: push
jobs:
  clippy:
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v4
      - name: Clippy
        run: cargo clippy --all-features --all-targets
  build:
    runs-on: [self-hosted, linux]
    needs: clippy
    steps:
      - name: Debug
        run: cargo build
      - name: Release
        run: cargo build --release
  test:
    runs-on: [self-hosted, linux]
    needs: build
    steps:
      - name: Test
        run: cargo test
  format:
    runs-on: [self-hosted, linux]
    needs: clippy
    steps:
      - name: Check format
        run: cargo fmt --check
  documentation:
    runs-on: [self-hosted, linux]
    needs: clippy
    steps:
      - name: Build documentation
        run: cargo doc -j1
