name: Check
on: push
jobs:
  build:
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v3
      - name: Debug
        run: cargo build
      - name: Release
        run: cargo build --release
  test:
    runs-on: [self-hosted, linux]
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Test
        run: cargo test
  format:
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v3
      - run: cargo fmt --check
